"""Plain-text digest builder for attack surface change alerts."""

from __future__ import annotations

import re
from typing import Any

from asm.scoring import TIER_RANK


def sanitize_header_field(val: str, max_len: int = 100) -> str:
    """Strip all CR, LF, and non-printable control characters from a header value."""
    # Remove CR, LF, and all ASCII control characters (< 0x20 and 0x7f)
    cleaned = re.sub(r"[\r\n\x00-\x1f\x7f-\x9f]", "", str(val)).strip()
    return cleaned[:max_len]


def sanitize_body_field(val: Any, max_len: int = 200) -> str:
    """Sanitize and length-cap untrusted text from scan data for inclusion in email body."""
    if val is None:
        return ""
    # Strip non-whitespace control characters (< 0x20 and 0x7f-0x9f except \t, \n, \r)
    cleaned = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f]", "", str(val))
    # Replace carriage returns and newlines with spaces to prevent line breaking
    cleaned = re.sub(r"[\r\n]+", " ", cleaned).strip()
    if len(cleaned) > max_len:
        return cleaned[: max_len - 3] + "..."
    return cleaned


def build_alert_digest(
    domain_name: str,
    scan_run_id: int,
    changes: list[dict[str, Any]],
    triggering_changes: list[dict[str, Any]],
) -> tuple[str, str]:
    """Build subject and plain-text body for an attack surface alert email.

    Args:
        domain_name: Domain investigated.
        scan_run_id: ID of the scan run that detected the changes.
        changes: Full list of all detected changes (used for summary counts).
        triggering_changes: Exposure changes at or above threshold, sorted highest severity first.

    Returns:
        tuple[subject, body]: The sanitized email subject and plain-text body.
    """
    clean_domain = sanitize_header_field(domain_name, max_len=100)
    count = len(triggering_changes)
    exposure_word = "exposure" if count == 1 else "exposures"

    # Sort triggering changes by severity descending (CRITICAL -> INFO), then asset
    sorted_triggering = sorted(
        triggering_changes,
        key=lambda ch: (
            -TIER_RANK.get(str(ch.get("severity", "INFO")).upper(), 0),
            str(ch.get("asset", "")),
        ),
    )

    # Highest severity among triggering changes
    highest_sev = "EXPOSURE"
    if sorted_triggering:
        highest_sev = sanitize_header_field(
            sorted_triggering[0].get("severity", "EXPOSURE"), max_len=16
        )

    # Subject header: CR and LF strictly stripped
    raw_subject = f"[Exposight] {highest_sev}: {count} new {exposure_word} on {clean_domain}"
    subject = sanitize_header_field(raw_subject, max_len=255)

    # Compute summary counts by tier
    summary_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
    for ch in changes:
        sev = str(ch.get("severity", "INFO")).upper()
        if sev in summary_counts:
            summary_counts[sev] += 1

    body_lines = [
        "ASM Attack Surface Alert",
        "======================================================================",
        f"Domain:      {clean_domain}",
        f"Scan Run ID: {scan_run_id}",
        "",
        "Summary of Detected Changes:",
        f"  - CRITICAL: {summary_counts['CRITICAL']}",
        f"  - HIGH:     {summary_counts['HIGH']}",
        f"  - MEDIUM:   {summary_counts['MEDIUM']}",
        f"  - LOW:      {summary_counts['LOW']}",
        f"  - INFO:     {summary_counts['INFO']}",
        "",
        f"Triggered Exposures ({count}):",
        "----------------------------------------------------------------------",
    ]

    for idx, ch in enumerate(sorted_triggering, start=1):
        sev = sanitize_body_field(ch.get("severity", "UNKNOWN"), max_len=16)
        ctype = sanitize_body_field(ch.get("change_type", "UNKNOWN"), max_len=64)
        asset = sanitize_body_field(ch.get("asset", "UNKNOWN"), max_len=100)
        detail = sanitize_body_field(ch.get("detail", ""), max_len=200)
        evidence = sanitize_body_field(ch.get("evidence", ""), max_len=64)

        body_lines.append(f"[{idx}] Severity: {sev}")
        body_lines.append(f"    Type:     {ctype}")
        body_lines.append(f"    Asset:    {asset}")
        if detail:
            body_lines.append(f"    Detail:   {detail}")
        if evidence:
            body_lines.append(f"    Evidence: {evidence}")
        body_lines.append("")

    body_lines.extend(
        [
            "----------------------------------------------------------------------",
            "This is an automated attack surface monitoring alert generated by Exposight.",
        ]
    )

    body = "\n".join(body_lines)
    return subject, body
